### ISSUE TITLE
One click login

### ISSUE THREAD

**Issue by Muhncheez** [atomizer/muledump#101]
I need help using one click login. I have AutoIT downloaded, and I am trying to run it but I keep getting this error. http://prntscr.com/breicm Can anyone help?

**Comment by Nightfirecat** [comment]
Can you try using the "Run as administrator" option for `mulelogin.au3`?

**Comment by Muhncheez** [comment]
I do not get the option to run as administrator for mulelogin.au3 .

**Comment by Nightfirecat** [comment]
Try running AutoIt (the program itself, not the script), then selecting the script to run. If that doesn't work, try running AutoIt as an administrator and repeating the process.

**Comment by Muhncheez** [comment]
Yup. Everything seems to be working fine, although I can not really tell since maintenance. it does however try to launch, Thanks@

**Comment by Nightfirecat** [comment]
Sounds good. From now on, it shouldn't need to be re-initialized that way; it should just launch properly once the servers are back up.

**Comment by Nightfirecat** [comment]
Just opened #102 to make the error message more clear, and [added this issue to the wiki as a troubleshooting item](https://github.com/atomizer/muledump/wiki/Troubleshooting#running-muleloginau3-gives-an-unable-to-write-registry-error-when-i-am-the-system-administrator).
