### ISSUE TITLE
Cant rename file

### ISSUE THREAD

**Issue by Jaggtastic** [atomizer/muledump#103]
Dont know if anyone still does this or looks at this but, when i go into file (accounts.sample.js), right click, there is no option saying rename. So I go to properties and try it there. No luck. If you can help please reply. Via- Windows 10

**Comment by Nightfirecat** [comment]
Is this issue specific to the muledump folder, or are you seeing it in other parts of your system as well?

[If the issue is the latter, this may help.](http://answers.microsoft.com/en-us/windows/forum/windows_10-files/i-cant-rename-files-in-windows-10/6d93ff11-a0c7-40a6-90ab-d3d913b29700?auth=1)
