### ISSUE TITLE
New items in-game

### ISSUE THREAD

**Issue by bic81394** [atomizer/muledump#108]
Well, as per NightFireCat here it is.
The next issue, one more easily fixable than the vault issue.
There are new items in the game with image in the dump.
Particularly the RosenBlade Skin, and the Ring of Decades.

**Comment by Nightfirecat** [comment]
@atomizer, if it's not too much trouble, could we get a process in place so that anyone can run the necessary conversion scripts to create the new item definitions and sheet? Would make it easier to update local copies or submit PRs for this type of change.
