### ISSUE TITLE
Grey page

### ISSUE THREAD

**Issue by kuroshitsuji123** [atomizer/muledump#111]
I have read other pages, and none of them seem to help me. Here is my console after pressing Ctrl+Shift+I: 

file:///C:/Users/OWNER~1.DES/AppData/Local/Temp/Rar$EXa0.308/muledump-master/accounts.js Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by Nightfirecat** [comment]
It sounds like you have not correctly named your `accounts.js` file. Can you please [ensure that your file extensions are turned on](http://windows.microsoft.com/en-US/windows7/Show-or-hide-file-name-extensions), then make sure you have an `accounts.js` file located at:

> C:/Users/OWNER~1.DES/AppData/Local/Temp/Rar$EXa0.308/muledump-master/accounts.js

**Comment by kuroshitsuji123** [comment]
I have tried making it "accounts.js, as well as accounts". Both times I get the grey page.

**Comment by kuroshitsuji123** [comment]
https://gyazo.com/162981596c5aed30658d1d02171c2881

**Comment by Nightfirecat** [comment]
Oh. You need to actually unpack all of the files from the ZIP archive. (use the "Extract to" button up top) Once you do that, make sure the accounts file is named `accounts.js`.

**Comment by kuroshitsuji123** [comment]
When winrar asks me 'so and so was modified in the archive, do you wish to update?', am I supposed to say yes or no

**Comment by Nightfirecat** [comment]
The idea is that you're not supposed to be modifying files in the archive; you're supposed to un-archive the full folder before making changes. As of now, it looks like you've missed [step 1 of the "How-to"](https://github.com/atomizer/muledump#howto).

**Comment by kuroshitsuji123** [comment]
Does unpack mean extract?

**Comment by Nightfirecat** [comment]
Yes. Here's a video if it helps: https://www.youtube.com/watch?v=EFK4WACSV5A

**Comment by kuroshitsuji123** [comment]
Now it looks like this: https://gyazo.com/d987b5cd4a23e253617f30c58ecaa710

**Comment by Nightfirecat** [comment]
You still have not unpacked all of the files. Once you unpack ALL of the files, you must open "muledump.html" in the folder where you've unpacked them. Try following Techmech's guide from start to finish: https://www.youtube.com/watch?v=HMt38yRRZaI

**Comment by kuroshitsuji123** [comment]
Ok, it works now. But now, I can only see 2 of my mules. It shows up in the items part, but the rest of my mules are missing.

**Comment by kuroshitsuji123** [comment]
Oh, nevermind everything works. THanks for your help, I really appreciate it!
