### ISSUE TITLE
Gray Screen

### ISSUE THREAD

**Issue by IronTailed** [atomizer/muledump#112]
When I try to open the .html file, I get this screen:
![screen shot 2016-10-04 at 7 40 48 pm](https://cloud.githubusercontent.com/assets/22627594/19096504/e0a5381e-8a6a-11e6-92b0-3fa6e2262d8c.png)

Is this because I am on an non-personal computer? 
Please help me.

**Comment by Nightfirecat** [comment]
Can you open your browser console (in Chrome this is done with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>), choose the "Console" tab, then refresh the page? Please paste whatever appears there so we can take a look at it.

**Comment by IronTailed** [comment]
Do you mean this?
![screen shot 2016-10-05 at 7 53 30 am](https://cloud.githubusercontent.com/assets/22627594/19112086/e1c7fdba-8ad0-11e6-9054-fc3f3a8a5629.png)

It shows that the error is where my account credentials are.

**Comment by IronTailed** [comment]
I don't exactly want to share my login credentials, but here is an example what I have on line 10:

‘rotmg@gmail.com’: ‘password’,

**Comment by IronTailed** [comment]
![screen shot 2016-10-05 at 8 00 39 am](https://cloud.githubusercontent.com/assets/22627594/19112271/e423086a-8ad1-11e6-8306-867257990277.png)

**Comment by atomizer** [comment]
You are using fancy quotes, they are not a valid delimiter in javascript.
Replace them with regular (vertical) ones. Try using a different editor.

**Comment by IronTailed** [comment]
I'm using textedit on Mac(default program). Could you show me what regular quotes look like compared to fancy ones?

**Comment by IronTailed** [comment]
Do you have any text editors that you would like to recommend?

**Comment by atomizer** [comment]
Here is a regular quote: '
I can recommend Sublime Text

**Comment by IronTailed** [comment]
Still doesn't work. I'm on an organizational computer that blocks ROTMG, would that affect anything? With the fancy quotes, it wouldn't work at home when ROTMG was unblocked.

**Comment by Nightfirecat** [comment]
It shouldn't matter if you're on an organizational computer; the issue is that you have a poorly-formatted `accounts.js` file. You can paste the contents of your `accounts.js` file into a linter like http://jshint.com/ to see where there are errors. (You can ignore warnings about undefined variables or missing semicolons)

**Comment by IronTailed** [comment]
![screen shot 2016-10-05 at 2 03 21 pm](https://cloud.githubusercontent.com/assets/22627594/19127251/3a83d2a4-8b0c-11e6-9c9e-448361caa6fa.png)

It says unrecoverable syntax error

**Comment by Nightfirecat** [comment]
That sounds bad. Can you copy+paste line 10 (replacing your email and password with dummy values) here?

**Comment by IronTailed** [comment]
'yep@yep.net': 'yep',

**Comment by IronTailed** [comment]
That's line 10

**Comment by Nightfirecat** [comment]
I don't see anything wrong with that... I am, of course, assuming your password doesn't have any single-quotes in it (`'`) of course, because that would cause problems.

Side-note, we need to think of a better way to troubleshoot `accounts.js` problems in cases like these... Not having easy access to the files (because of account credentials) makes debugging a big hassle.

**Comment by smartymarv** [comment]
saw someone with a similar issue recently, did you remember to rename accounts_sample.js to accounts.js? just makin sure

**Comment by IronTailed** [comment]
yes

**Comment by IronTailed** [comment]
Unrelated fact: Rotmg gets stuck on 100% loading for some reason (in browser)

**Comment by IronTailed** [comment]
// editor with syntax hilighting is recommended (for example, notepad++ or textmate)

accounts = 

// Put your data here as shown below. Don't forget the commas and quotes!
// If your emails or passwords contain single quotes,
// escape them with backslashes (\) like this: 'pass\'word'


'123@123.net': '123',



}// don't delete this line!


// how many characters are displayed in each row (within one account)
rowlength = 7

// change to 1 to switch to testing
testing = 0

// change to 1 to enable price display in tooltips
prices = 0

// change to 1 to enable one-click login (run lib/mulelogin.au3 first)
mulelogin = 0

// 0 = use smart layout (fill empty spaces)
// 1 = show account boxes row by row
nomasonry = 0







This is my accounts.js.

**Comment by Nightfirecat** [comment]
Line 3 should read as follows: (you are missing the open curly bracket &mdash; `{`)

```
accounts = {
```

[See line 3 of the sample file.](https://github.com/atomizer/muledump/blob/master/accounts_sample.js#L3)

**Comment by IronTailed** [comment]
Alright, now it works
