### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by AdventAngel** [atomizer/muledump#113]
Reloading the accounts puts up an error. 

The top-left corner states: (email here): server error

The errors on the accounts (they're grayed out) say: 
loading data
server error
full response:{"count":0,"created":"2016-10-06T06:21:54Z","lang":"en-GB","results":null}

Any ideas as to what the cause is and how to fix it?

**Comment by ProfNyan** [comment]
Having the same problem here. I think this is a new issue with muledump related to the new AGC update, but I could be entirely wrong. Maybe DECA has been prodding around the game's code as of recently for the new content update coming soon and it threw a wrench in muledump's operations. Either way, you aren't the only one.

**Comment by ChiefEagle** [comment]
got it too :\

**Comment by AdventAngel** [comment]
Err... okay. It just fixed itself just then. Maybe it's something to do with the client then, and Deca may have been just updating something in the background~ 

Thanks anyways, and if anyone else still has this problem or knows what caused it, let us know~
