### ISSUE TITLE
Fix the sprite sheet (renders.png) for update 27.7.X6

### ISSUE THREAD

**Issue by loveens** [atomizer/muledump#116]
Hello, it's been a few days since Deca added new dungeons and items to thte game, but new keys, items and consumables are not displaying in the muledump correctly, just as IDs. Please add them to renders.png. 

Deca's announcement about new update: https://www.reddit.com/r/RotMG/comments/56zekm/patch_notes_277x6_content_returns/

**Comment by atomizer** [comment]
Done, sorry about that.

**Comment by loveens** [comment]
Thank you!
