### ISSUE TITLE
Muledump not working (mac)

### ISSUE THREAD

**Issue by Cawvix** [atomizer/muledump#121]
I don't know why I cannot get it to work. I have followed the instructions: edited accounts.js file, adding my email and passwords replacing only the sample text. Then I renamed it accounts.js. When opening the muledump.html, I come up with this screen in both Chrome and Safari:
<img width="1280" alt="screen shot 2016-12-03 at 5 41 31 pm" src="https://cloud.githubusercontent.com/assets/24362678/20863461/c141a400-b97f-11e6-9175-6142c3a7e55f.png">

Help?

**Comment by Nightfirecat** [comment]
Can you open your browser console (in Chrome this is done with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>), choose the "Console" tab, then refresh the page? Please paste whatever appears there so we can take a look at it.

**Comment by Cawvix** [comment]
Invalid token? This seems to imply I did something wrong with the passwords but... I'm pretty sure I didn't.
<img width="1280" alt="screen shot 2016-12-04 at 11 48 18 am" src="https://cloud.githubusercontent.com/assets/24362678/20868744/9f30bc78-ba17-11e6-8d16-f4235a93eb51.png">

**Comment by Cawvix** [comment]
Here's the error
<img width="1277" alt="screen shot 2016-12-04 at 11 50 53 am" src="https://cloud.githubusercontent.com/assets/24362678/20868760/f0a05514-ba17-11e6-8390-e34a56126693.png">

**Comment by UnicoRush** [comment]
Hi Cawvix,

I suppose you get this error because you typed '|' character above
passwords.

BR,
Unicorush

2016-12-04 20:51 GMT+01:00 Cawvix <notifications@github.com>:

**Comment by atomizer** [comment]
fancy quotes strike again. see
https://github.com/atomizer/muledump/issues/96#issuecomment-191307519

**Comment by Cawvix** [comment]
Thanks for the help! I managed to figure the "smart quotes" error on my own... I used to have this problem when using Java...

**Comment by Nightfirecat** [comment]
Curse you, fancy quotes!
