### ISSUE TITLE
Colon in password.

### ISSUE THREAD

**Issue by BrennanT** [atomizer/muledump#124]
Having a colon (":") in your password breaks the script by cutting off everything after and including the colon in your password. Is there a fix for this or a way to escape the colon?

**Comment by Nightfirecat** [comment]
Just a hunch, can you try escaping it in the string? eg. `"te:st"` --> `"te\:st"`

**Comment by Nightfirecat** [comment]
...so did that work?

**Comment by BrennanT** [comment]
It was an issue with a Java program that wasn't writing to the accounts.js correctly.
