### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by ImOnDisplay** [atomizer/muledump#131]
Hello, I'm hoping someone can help me out here. My muledump seems to have broken. when i try to launch it's just a gray screen with one little box in the top left. I've deleted and reinstalled the program. i am fairly confident that i have everything set up properly, renamed the accounts file. i don't get any error messages, just when i try to open it in chrome it never seems to work. any help is greatly appreciated, thank you.

**Comment by Nightfirecat** [comment]
Can you open your browser console (in Chrome this is done with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> <u>or</u> <kbd>Cmd</kbd> + <kbd>Opt</kbd> + <kbd>I</kbd>), choose the "Console" tab, then refresh the page? Please paste whatever appears there so we can take a look at it.

**Comment by ImOnDisplay** [comment]
i figured out it was my zonealarm blocking it, i fixed it now.
