### ISSUE TITLE
Auto Login through Local Client

### ISSUE THREAD

**Issue by CrunchyFlake** [atomizer/muledump#134]
How do i set the auto login to open up with a client located locally on my comouter also is thete a way to make all the rows of char the same height in the sense in the first row the char box  with the highest height is the highest height for all other ones in the row (even if they are smaller).This is so that the char boxes that are shorter dont stick to each other.

**Comment by Nightfirecat** [comment]
You can modify your mulelogin.au3 [based on the comments at the bottom of the file](https://github.com/atomizer/muledump/blob/master/lib/mulelogin.au3#L130) to modify the client opened with One-click login.

Also, to change the row filling, set `nomasonry = 1` in your accounts.js file: https://github.com/atomizer/muledump/blob/master/accounts_sample.js#L31

**Comment by CrunchyFlake** [comment]
ty so much ur awesum
