### ISSUE TITLE
I cant see chest contents

### ISSUE THREAD

**Issue by Piincakes** [atomizer/muledump#146]
none of my chests items are loading in, even though i have tried reinstalling and reloading muledump multiple times. is there any way to fix this? I do have items in them, they just aren't showing up.
![image](https://user-images.githubusercontent.com/30891276/29158778-4dc723be-7d7a-11e7-8fcc-72549409f771.png)
I should also add that this is also happening with gift chests.

**Comment by tischepe** [comment]
Look at https://github.com/atomizer/muledump/pull/137
