### ISSUE TITLE
Muledump Reload all

### ISSUE THREAD

**Issue by MatKulik** [atomizer/muledump#60]
Hello I have noticed a little problem today.
I want to refresh all my mules so they are updated but it takes really long.
I click reload all and it takes so long to load my mules
Also most of them get server error when it was perfectly working yesterday
I have tried the new updated one but still the same
I have restarted by computer but still the same

**Comment by iObsidian** [comment]
I do experience the same issue. I'm using Chrome and the latest version of muledump.
The mules load really slowly and some of them get server error, even tho there is nothing wrong with them. Tbh, it doesnt really matter because when I refresh them again it works.

**Comment by Nightfirecat** [comment]
@MatKulik, Are you still experiencing this issue?

@atomizer, This seems like a stale issue, and I'm seeing no repro.
