### ISSUE TITLE
Kongregate Muledump

### ISSUE THREAD

**Issue by jcw4262000** [atomizer/muledump#64]
Don't know if this is my own problem or something, but now that i try to register new mules on Kongregate, it talks about needing an admin console in order to get the guid and secret. Any help is appreciated, I already know how to get the guid.

**Comment by Nightfirecat** [comment]
What browser are you using? I can probably paste some directions w/ screenshots to explain what to do.

**Comment by jcw4262000** [comment]
I'm using chrome. Thank you for the help.

**Comment by Nightfirecat** [comment]
![gif of steps 1-7 below](http://i.imgur.com/mh8Q2Le.gifv)

1. Open [the main page for this repository](https://github.com/atomizer/muledump)
2. Scroll down to the section reading ["How do I use it with a Kongregate account?"](https://github.com/atomizer/muledump#q-how-do-i-use-it-with-a-kongregate-account)
3. Copy the bolded script (starting with `document`, ending with `gameAuthToken()})`)
4. Visit the [Realm of the Mad God game page](http://www.kongregate.com/games/wild_shadow/realm-of-the-mad-god) on Kongregate while logged in
5. Hit F12
6. Select the "Console" tab
7. Paste the script and hit enter

Once you get that info, remove the section in your accounts.js file that looks like this:

```
'email': 'pass',
'email2': 'pass2',
```

then replace it with one that looks like this:

```
'yourGUID': 'yourSECRET',
'yourOtherGUID': 'yourOtherSECRET',
'webAccountEmail': 'webAccountPass',
```

**Comment by jcw4262000** [comment]
I know how to do this. I mean that it always worked before this way before, but after the data migration on ROTMG, whenever i do these steps it says I need an admin console.

**Comment by Nightfirecat** [comment]
Ah, ok - sorry I misunderstood your problem...

Can you please provide as much detail on this as possible? Include screenshots?

**Comment by jcw4262000** [comment]
I basically copy that text and paste into the console. What I get is
Datastore writes have been disabled by an application administrator. Writes can be re-enabled in the admin console.

**Comment by jcw4262000** [comment]
Also, is there anyway for one click login to work for kongregate accounts?

**Comment by Nightfirecat** [comment]
So you get an error of sorts reading exactly:

> Datastore writes have been disabled by an application administrator. Writes can be re-enabled in the admin console.

But where do you see it? Do you see this in the Javascript console, or does the web page load with a white background and that text on it?

Yes, you should be able to use one-click login with any type of account, so long as you can get muledump to connect to it.

**Comment by jcw4262000** [comment]
![image](https://cloud.githubusercontent.com/assets/10663304/5886004/e16433b0-a347-11e4-831f-d07041948e1a.png)
It looks like this. Just that white background. Could you tell me how to use one click login for kongregate? It works for the regular ones but on the kongregate ones it just gives me the rotmg home page with no user saved.

**Comment by jcw4262000** [comment]
![image](https://cloud.githubusercontent.com/assets/10663304/5886020/2d16a518-a348-11e4-922e-265af9be9b5d.png)
It looks like the white page with the text. Also, could you tell me how to use it with a kongregate account? It works on the normal ones but on kongregate it just gives me the home page with no user saved.

**Comment by atomizer** [comment]
I changed the snippet in readme, please try again.
No, kongregate accounts are not supported by one-click.

**Comment by Nightfirecat** [comment]
D'oh, should've remembered the domain change.

**Comment by jcw4262000** [comment]
Thank you guys. It works again now.
