### ISSUE TITLE
For Kongregate One Click Login

### ISSUE THREAD

**Issue by jcw4262000** [atomizer/muledump#66]
So I don't know where we're supposed to put suggestions, but for kongregate accounts could you like write a program to copy and paste a specific url into the browser for the one click login? You could do this by making another seperate notepad to store that do not share link for kongregate rotmg accounts.

**Comment by Nightfirecat** [comment]
You can modify the mulelogin.au3 file to open a different link, rather than the homepage of RotMG that it provides.

I'd refer to [this thread](https://web.archive.org/web/20130522040135/https://forums.wildshadow.com/node/27826) as well as these videos ([1](https://www.youtube.com/watch?v=wmswQ4LUuKA) [2](https://www.youtube.com/watch?v=MZydySZEOxg)) for more on this.

**Comment by jcw4262000** [comment]
Sorry, but I do not get what this means at all cause I'm not good at programming. I mean could you just change muledump or something to have another notepad that's in the from "guid": "flash projector code", and then when you click on the button in muledump for one click login, have the program find the guid from the first one, find the same guid from the second one, and use the flash projector code from the other one to post into the url.

**Comment by Nightfirecat** [comment]
Well, from what I see, it'd take some reworking to get mulelogin.au3 to accept Kongregate credentials... Not to say it can't be done, but I wouldn't consider it something to expect too soon.

@atomizer If you'd like, assign this issue to me, and I'll look into getting one-click to work with Kong. Seems like it just needs to check the "email" field for an email-like structure (including `@`), and opening a Kong-param'd URL instead.

**Comment by atomizer** [comment]
IIRC kongregate loads realmofthemadgod.com/kongregate.html in a frame - I
suggest looking at how it passes the auth data to it. (I don't think
writing the .sol will be useful at all)
Also you don't need to ask, if you accomplish anything just send a PR.

**Comment by Nightfirecat** [comment]
Can do. Working on some features for another repo in the meantime, so response time here will be delayed somewhat, but I think this is definitely achievable.

**Comment by jcw4262000** [comment]
Ok. I completely didn't get what you guys were talking about, but thank you. Kongregate has gotten really annoying with all the lag and ads recently.
