### ISSUE TITLE
My Kongregate account won't show up

### ISSUE THREAD

**Issue by Manalife** [atomizer/muledump#67]
After updating to the newest version, my kongregate account doesn't show up on muledump.
All the other "normal" accounts does show up. I have put it in account.js like this:
'GUID': 'Secret',
While using reload all, I can see that muledump have register the kong acc because of "waiting requests: 1".

**Comment by atomizer** [comment]
This is pretty strange, both kong accounts i'm testing on work fine. I havent heard of anyone else having similar problem. Is it still happening or it was a temporary thing?

**Comment by Manalife** [comment]
Yes, each time I open my muledump i still get "waiting request: 1" but the kong account doesn't show up.

**Comment by atomizer** [comment]
Are there any errors in console (Ctrl+Shift+J on Chrome, Ctrl+Shift+K on Firefox) when you refresh?

**Comment by Manalife** [comment]
I don't know, I used Firebug(somewhat similiar to webconsole) to find the infos.

**Comment by atomizer** [comment]
it doesnt matter, could you... check?..

**Comment by Manalife** [comment]
You mean console and then tha tab net (not using the eng. version)? Where all these GET http://kongregate.com/games/WildShadow/realm-of-the-mad-god ... etc.

**Comment by atomizer** [comment]
No. Open it when you have muledump open, look at console tab, and reload the kong account.

**Comment by Manalife** [comment]
No errors

**Comment by atomizer** [comment]
Ok, negative result is a still a result. I'm afraid I have no idea why that particular account might not load. I guess we'll have to wait and see whether anyone else has this problem.

**Comment by Manalife** [comment]
Made a new account and tested with it... same result now with  "waiting request: 2". Also tested on chrome, same result.(<--- no errors there in console).

**Comment by Manalife** [comment]
Made a new account and it worked... so something withc changing email on kong resulted with errors...

**Comment by Manalife** [comment]
I changed email on the test account and it still worked... I guessing that the problem has something do with the 'GUID', because 'Secret' is same length and format while on 'GUID' there is one with my userid (test) and the one that is not working (email). Also on kong accounts, muledump cant regnoze any errors even when the login credentials is wrong (so it's hard to know if i either put in wrong info or that the acc is simpy f*cked up).

**Comment by Nightfirecat** [comment]
@Manalife, can you try following the steps [in this issue](https://github.com/atomizer/muledump/issues/76#issuecomment-162138298)? It's possible you have an older copy of muledump and an old copy of `libs/realmapi.js` which might cause this. (disclaimer: I don't actually know that this will solve the problem, but I have a bit of a hunch)
