### ISSUE TITLE
Flash Player

### ISSUE THREAD

**Issue by jcw4262000** [atomizer/muledump#68]
Ok, so since muledump one click login needs the adobe flash player that's not included with google chrome, I obviously need that for it to work. However,  today on 4/17 the other plug in disappeared and now all I'm left with is the google chrome adobe flash player. This usually wouldn't be a problem, but whenever I try to redownload the other adobe flash player, it never shows up and now one click log in just takes me to realmofthemadgod.com. I've tried redownloading it over ten times, and it's getting really frustrating. Any help is appreciated, thanks.

**Comment by atomizer** [comment]
try this:
http://community.kabam.com/forums/showthread.php?458061-Chrome-is-extremely-laggy

**Comment by jcw4262000** [comment]
It worked! Thanks a lot for the help. Also, for using one click login with flash projector, what are you supposed to put after ShellExecute('C:\Users\Guest\Desktop\rotmg.exe')? It opens the flash projector, but that's all, don't' know how to put the swf code in..

**Comment by Nightfirecat** [comment]
You have to run the `ShellExecute()` command with two parameters: the first is the location of the flash player, and the second is the actual SWF location. I wrote a short script that'll grab the latest SWF version every time you run it - you can comment out the current ShellExecute line and replace it with this new line:

     ShellExecute('C:\Users\Guest\Desktop\rotmg.exe', 'http://www.realmofthemadgod.com/AGCLoader'&BinaryToString(InetRead("http://www.realmofthemadgod.com/version.txt"))&'.swf')

**Comment by jcw4262000** [comment]
Ok, it opens the rotmg thing, but it says there's a version loading error something. I think you're using the wrong code, the one i use is https://realmofthemadgodhrd.appspot.com/AssembleeGameClient1424386506.swf. Also, how do I look at previous closed issues because I may want to look at this later.

**Comment by Nightfirecat** [comment]
Yeah, I think you're right about that - I haven't updated it to use the new SWF location, so you'll just have to change it to the below (`realmofthemadgod` -> `realmofthemadgodhrd`):

    ShellExecute('C:\Users\Guest\Desktop\rotmg.exe', 'http://www.realmofthemadgod.com/AGCLoader'&BinaryToString(InetRead("http://www.realmofthemadgod.com/version.txt"))&'.swf')

**Comment by jcw4262000** [comment]
I think you have to replace the AGC with AssembleeGameClient, still has version loading error

**Comment by jcw4262000** [comment]
Also, the http: part to https:

**Comment by Nightfirecat** [comment]
ShellExecute('C:\Users\Guest\Desktop\rotmg.exe', 'https://www.realmofthemadgodhrd.appspot.com/AssembleeGameClient'&BinaryToString(InetRead("http://www.realmofthemadgod.com/version.txt"))&'.swf')

That should do the trick, then.

**Comment by jcw4262000** [comment]
Still doesn't work, just opens the flash projector and stays like that.

**Comment by jcw4262000** [comment]
Also, kongregate rotmg doesn't work anymore for the non default version of adobe flash player, default still works, anyway to fix this?

**Comment by jcw4262000** [comment]
Maybe get rid of the www after https:?

**Comment by Nightfirecat** [comment]
I just tried this in muledump myself and found it to work:

    ShellExecute('C:\Users\Nightfirecat\Desktop\flashplayer_16_sa.exe', 'https://realmofthemadgodhrd.appspot.com/AssembleeGameClient'&BinaryToString(InetRead("http://www.realmofthemadgod.com/version.txt"))&'.swf')

**Comment by jcw4262000** [comment]
Ok, so now it loads the flash projector, but it doesn't log me in (I tried multiple times)?

**Comment by Nightfirecat** [comment]
Looks like the URL needed to be changed in 2 places... This would actually be worth making a change to the whole file for - I'll make a pull request for it. You'll have to [add the line above to this file like before](https://github.com/atomizer/muledump/issues/68#issuecomment-94610977), but with the new file, it should actually work properly.

**Comment by jcw4262000** [comment]
Alright thanks, it works now. Is there any way to solve the problem with kongregate rotmg not working without the default adobe flash player? It has the version loading error if you use the separate one.

**Comment by Nightfirecat** [comment]
I can honestly say I don't know about that one - I've never owned a Kongregate account, so I've never been able to test that.

What do you mean by "default adobe flash player"? The Adobe Flash Projector?

**Comment by Nightfirecat** [comment]
Hm... It may have something to do with the fact that it looks like Kongregate stores its account information within `#SharedObjects/ID/www.realmofthemadgod.com/KongregateRotMG.sol` rather than `#SharedObjects/ID/realmofthemadgodhrd.appspot.com/RotMG.sol`.

I'm not sure I'll be sufficiently able to debug this, but it looks like one-click login would have to be rather heavily retooled in order to support Kongregate accounts. If you've got the know-how and the time to work on it, feel free, but I don't think there's going to be a solution to getting Kong accounts to work with one-click anytime soon otherwise.

**Comment by jcw4262000** [comment]
I'm talking about the regular kongregate rotmg website, nothing to do with muledump. After they disabled the non default adobe flash player for google chrome and you had to reenable it, kongregate now just gives me a version loading error if you use the non default one. The default one is the one you automatically get with google chrome, the non default one is the one you download from the website.

**Comment by jcw4262000** [comment]
As for oneclick login for kongregate accounts, would it be that hard to write a program like this?
'kongregate:six numbers': 'kongregate source code', as a separate document.
Then whenever you click on the login button, it looks at that document, matches the "kongregate:six numbers," and pastes the kongregate source code into the url. If it might be hard to distinguish between kongregate and normal accounts, could you make another version for kongregate only?

**Comment by jcw4262000** [comment]
poop

**Comment by jcw4262000** [comment]
Also, when I changed line 107, it doesn't work with rotmg one click login in browser now. Is it supposed to be like this?

**Comment by Nightfirecat** [comment]
@jcw4262000 The account was switched correctly for browser but not for projector before the change, and now it doesn't work properly for the browser, but it *does* for projector?

**Comment by jcw4262000** [comment]
yeah

**Comment by jcw4262000** [comment]
Just checking, the only line you changed was 107 right? Cause that's the only one I changed, that might be the problem if so.

**Comment by Nightfirecat** [comment]
> particularly [line 107](https://github.com/Nightfirecat/muledump/blob/oneclick-domain-fix/lib/mulelogin.au3#L107) and [line 118](https://github.com/Nightfirecat/muledump/blob/oneclick-domain-fix/lib/mulelogin.au3#L118).

Assuming you already added the new line at the bottom (like I detailed in earlier comments), yes - the only other line I changed was 107. I'll take a look at this later tonight.

**Comment by Nightfirecat** [comment]
Alright, found some time to look at it again. Try looking at the pull request I opened and use the new version of the mulelogin.au3 - it should write the character info to both locations, so you can then use your browser or flash player alike to open it just fine.

**Comment by jcw4262000** [comment]
Wait, so you want me to like copy that file info into my own? Any way of downloading it?

**Comment by Nightfirecat** [comment]
You can [copy the file into whatever text editor you use](https://raw.githubusercontent.com/Nightfirecat/muledump/oneclick-domain-fix/lib/mulelogin.au3) and save it over the old file, or you can [just download my fork of muledump](https://github.com/Nightfirecat/muledump/archive/oneclick-domain-fix.zip) and follow the normal installation steps - it'll include the updated file.

**Comment by jcw4262000** [comment]
It works now thanks. Anyway to solve the kongregate rotmg issue with non default flash player?

**Comment by Nightfirecat** [comment]
No idea about the issue there. You'll want to bring that up to Kongregate or to Kabam - it's not a Muledump issue, anyway.

**Comment by jcw4262000** [comment]
ok

**Comment by jcw4262000** [comment]
How about you fix muledump so it works with the default flash player then?

**Comment by Nightfirecat** [comment]
Fix...what exactly? What I understood from your last comment is that the Chrome Pepper Flash Player doesn't work correctly with RotMG when playing through Kongregate. If that's what you're referring to, it's *completely* unrelated to Muledump.

**Comment by jcw4262000** [comment]
That's correct, but one click login doesn't work with the default flash player either. So basically, you can have kongregate working with no one click log in, or vise versa.

**Comment by Nightfirecat** [comment]
You're going to have to be a little more specific - is this a flash player issue or a Kongregate account issue? This comment thread's a little messy, so you'll have to excuse me if I'm not understanding what you're referring to.

What would help most, actually, would be if you could walk step through step what you're doing, and explain what you expect to have happen as opposed to what actually happens.

**Comment by jcw4262000** [comment]
The issue I am referring to is how muledump one click log in doesn't work with the adobe flash player that comes with google chrome. Whenever I try to do this, it takes me to the website but doesn't log me in.

**Comment by Nightfirecat** [comment]
It's an open issue, see #41.

**Comment by jcw4262000** [comment]
Never mind, they fixed kongregate or something.
