### ISSUE TITLE
Doesnt work with kabam.com accounts

### ISSUE THREAD

**Issue by syx11** [atomizer/muledump#70]
I can get it to work on realmofthemadgod.com accounts however accounts connected to kabam do not work. Help?

**Comment by atomizer** [comment]
Sorry, kabam accounts are not supported at the moment. Duplicate of #58. There is no progress on this at the moment, if you're willing to research what the process of logging into a kabam account programmatically, feel free to share any details in that issue.

**Comment by syx11** [comment]
oh ok thanks
