### ISSUE TITLE
Flash Projector one click login

### ISSUE THREAD

**Issue by Drewbobsanders** [atomizer/muledump#71]
so i changed the mulelogin.au3 file to my flash projector location and it will open it but wont log into the account i clicked. just whatever one i was logged into last.

**Comment by jcw4262000** [comment]
Are you on chrome? Because if so it doesn't really work unless you do some stuff.

**Comment by jcw4262000** [comment]
Did it work before on chrome? Are you on the right flash player?

**Comment by Drewbobsanders** [comment]
No, I have it loaded in fire fox and try to use the one click login to my stand alone flash player. And it opens the game in flash, just not the account I want.

**Comment by Drewbobsanders** [comment]
No, I have it loaded in fire fox and try to use the one click login to my
stand alone flash player. And it opens the game in flash, just not the
account I want.

**Comment by kecleon** [comment]
If you follow this guide: http://www.mpgh.net/forum/599-realm-mad-god-cheats-hacks/544685-using-projector-muledumps-1-click-login.html
you have to modify the current mulelogin.au3's path finder. Mine's like this:

    $path = @AppDataDir & "\Macromedia\Flash Player\#SharedObjects\"
    $search = FileFindFirstFile($path & "*")
    $path &= FileFindNextFile($search) & "\localhost\RotMG.sol"

**Comment by Nightfirecat** [comment]
@kecleon Unless you're using a locally-saved SWF file as your client, da33ed6 should keep that from being an issue. Otherwise, it's an easy enough fix to [change this line to the below](https://github.com/atomizer/muledump/blob/da33ed6ca7cae891606793425ba510ae0cf636bb/lib/mulelogin.au3#L105):

    Local $paths[3] = ["www.realmofthemadgod.com", "realmofthemadgodhrd.appspot.com", "localhost"]


@Drewbobsanders Are you using the most recent version of Muledump?

**Comment by Drewbobsanders** [comment]
@Nightfirecat OMG!! TYSM!!! it works now. i kept messing with the paths and nothing and i kept moving stuff all over nothing. i know very little about scrippting but adding ,"localhost" and changing the paths2 to paths3 worked perfect. i forgot to put the comma and it didnt work at first lol. so i copy paste that line it works so great now tyvm
sorry im noob

**Comment by Nightfirecat** [comment]
Perhaps adding localhost could be useful for avoiding situations like these? At worst, it'll just create one extra file that isn't used anywhere.

**Comment by Drewbobsanders** [comment]
You gotta do you brah
