### ISSUE TITLE
Messy Consumable Sorting

### ISSUE THREAD

**Issue by Pfiffel** [atomizer/muledump#75]
In the totals, a lot of consumables are displayed in the order they were implemented in the game. This results in especially keys and skins being all over the place.
I include a script after constants which overwrites the tier values to achieve a more pleasant order, maybe it helps: http://pastebin.com/gFWRiPDk

**Comment by BlackRayquaza** [comment]
@Pfiffel you should make a pull request

**Comment by Nightfirecat** [comment]
I'll try to integrate this within the coming 2 weeks, just got a bunch of PRs that I'm working on at the moment.

**Comment by Nightfirecat** [comment]
Sorry for the wait; implemented and fixed in #80.
