### ISSUE TITLE
One Click Login No Longer Works

### ISSUE THREAD

**Issue by jcw4262000** [atomizer/muledump#81]
So for one click log in on google chrome, you need the alternate adobe flash player.
Before, you typed chrome://flags/#enable-npapi in google chrome but now npapi doesn't show up on there. Any solution to re-enable the alternate adobe flash player or other way to get one click log in to work on google chrome?

**Comment by Nightfirecat** [comment]
You'll have to excuse me if I sound rude, but this doesn't sound like a muledump problem -- it sounds like a Flash Player problem.

That said, if your issue is that one-click login doesn't work with Chrome's default Flash Player, that's already been outlined in #41. It could probably be fixed in a manner similar to #72, but it'll likely take more work, since pepper flash player's SOLs are saved in a vastly different directory. I'll see about looking at this in the next week or so.

**Comment by jcw4262000** [comment]
Ok, I will be waiting. Thank you for the help.

**Comment by Nightfirecat** [comment]
@jcw4262000, I'd advise you take a look at the commit I added to #72 &mdash; I think that should solve your Chrome problem. You should be able to [follow the same steps I outlined here](https://github.com/atomizer/muledump/issues/68#issuecomment-95396824) to incorporate the changes I made.

**Comment by jcw4262000** [comment]
Ok, I see if it works. Thank you.

**Comment by jcw4262000** [comment]
It works now, thank you alot.

**Comment by jcw4262000** [comment]
Also, I just wanted to let you know that my friend made a kongregate one click log in for me. I don't understand it, and I would upload it but it has my passwords and stuff. Basically has the stuff I wrote in my suggestion for one click log in for kongregate.

**Comment by Nightfirecat** [comment]
Would you be able to remove your account information and upload it somewhere? I'd love to take a look at it and integrate it in a pull request to the master branch if possible. :)

**Comment by jcw4262000** [comment]
It's like 
if(guid=='email'||guid=='email' etc.)
{
	var l = $('<a>').addClass('button');
	l.text('\u21d7');
	l.attr('href', 'muledump:' + toHex(guid) + '-' + toHex(accounts[guid]));
	l.attr('title', 'open this account');
	return l;
	}
if (guid=='kongregate code')
	{
	var l = $('<a target="_blank">button</a>').addClass('button');
	l.text('\u21d7');
1.attr('href','kongregate acc link')
l.attr('title', 'open this account');
	return l;
	}

**Comment by Nightfirecat** [comment]
Ah, alright. I've submitted a new issue to track this feature request specifically and I'll look into it when I get a chance. (Maybe this weekend, maybe next week; work is a time hog)
