### ISSUE TITLE
Cant load my account anymore, "failed many times"

### ISSUE THREAD

**Issue by quipham** [atomizer/muledump#87]
I can't use Muledump since last week. It show this error. 

![muledump](https://cloud.githubusercontent.com/assets/16282932/11771984/28934d32-a24a-11e5-8692-640b335995c6.png)

**Comment by Nightfirecat** [comment]
Has your password changed? That's the error message given by a failed request to load your characters.

**Comment by quipham** [comment]
This is realmofthemadgod.com bro. I checked and still login normaly with old pass :(

**Comment by Nightfirecat** [comment]
When have you last updated Muledump?

**Comment by quipham** [comment]
About one month ago. But i tried with 0.6.4 still same error.

**Comment by THEruuster** [comment]
Experiencing identical issue

**Comment by quipham** [comment]
I don't really understand what you mean, but it can be fixed?

**Comment by thebitey** [comment]
i'm also stuck with this issue.
was intermittent on saturday, and now completely locked out since sunday.
may be an issue with query.yahooapis.com as browser is continuously trying to connect before timeout.
![yeah](https://cloud.githubusercontent.com/assets/16287606/11778819/0a072814-a2ab-11e5-8069-c4c6628a38aa.jpg)

**Comment by quipham** [comment]
Yes the same. Last week were working good. Hope Nightfirecat can fix it soon. Thank ^^

**Comment by BlackRayquaza** [comment]
Strange, what browser are you using? @quipham @thebitey @THEruuster

**Comment by quipham** [comment]
Chrome bro

**Comment by thebitey** [comment]
firefox, but have tried chrome and no success there.

**Comment by BlackRayquaza** [comment]
@quipham Does the javascript console or the network tab show anything weird when you reload an account?

**Comment by quipham** [comment]
Just this :( and the same with IE like @thebitey 
xxx@gmail.com: failed too many times, giving up

**Comment by DoctorJosh** [comment]
Hello. I am currently experiencing this problem as well. It was working fine about two days ago then I tried it again and it just says failed. I tried changing my password and updating the accounts.js but nothing changed, not even when I open it with firefox.

**Comment by atomizer** [comment]
This is definitely a problem with access to YQL. Things to try:
- open [this link](https://query.yahooapis.com/v1/public/yql?q=select+*+from+xml+where+url%3D%22https%3A%2F%2Frealmofthemadgodhrd.appspot.com%2Fapp%2Finit%22&format=json) - it should show a json string starting with `{"query":{"count":1,"created":...`
  - if it doesn't, try using proxy or tor (for example, install zenmate)
  - if it does, I have no idea how to fix this

**Comment by atomizer** [comment]
Also try clearing your browser cache.
Also, waiting helped the last time this happened.

**Comment by DoctorJosh** [comment]
Oh. It worked. I just opened the link and cleared everything. Thank you.

**Comment by quipham** [comment]
Thank you it work again today.
