### ISSUE TITLE
Account Not Working

### ISSUE THREAD

**Issue by xAdrenaline** [atomizer/muledump#88]
I tried Kabam code and it doesn't work correctly.
     TypeError: document.getElementsByName(...).item(...) is null
That is what it returns.

Also, the Kongregate code worked for both of my accounts, but for one of them it says:
     Account credentials not valid
when I try to use muledump.

I know I took the right steps because one account works and the other doesn't.
I recently transferred from Kongregate to Kabam, is that an issue?

**Comment by Nightfirecat** [comment]
What line of what file is that error reported from?

**Comment by xAdrenaline** [comment]
I don't understand what that means, that's just what it returns when I copy paste the code into the console.

**Comment by xAdrenaline** [comment]
Do these characters have something to do with the issue? 
This:  _
This:  -

**Comment by xAdrenaline** [comment]
document.location.href = 'http://' + 'realmofthemadgodhrd.appspot.com/kabam/getcredentials?signedRequest=' + document.getElementsByName("signed_request").item(0).value
TypeError: document.getElementsByName(...).item(...) is null

**Comment by xAdrenaline** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15146410/11834367/6ebbe89e-a391-11e5-94fa-5185247cead5.png)

**Comment by Nightfirecat** [comment]
Ah, my mistake - I understand what you mean now.

**Comment by xAdrenaline** [comment]
Okay, so I still have the problem.  My account is originally from Kongregate, therefore, I can't use it from the Kabam website.  I can only play from the following two links.

http://www.kongregate.com/games/Wild_Shadow/realm-of-the-mad-god?acomplete=rea
http://www.realmofthemadgod.com/

So i got my GUID and Secret from the Kongregate website, but it's giving me the account credentials not valid.  I did this multiple times, so I am 100% sure i'm performing this task correctly.

Has anyone else done this with Kongregate transferred accounts?

**Comment by Nightfirecat** [comment]
So let me understand this -- you migrated from a Kongregate account to use a web account? Thus, you have a normal email/password combination which you can use to log in from www.realmofthemadgod.com? Try using that instead.

**Comment by xAdrenaline** [comment]
That is correct, but on the wiki there's no console code for www.realmofthemadgod.com.

**Comment by xAdrenaline** [comment]
I can retrieve GUID and Secret from using Kongregate but it gives me the "Account Credentials Not Valid" message when I run muledump.

**Comment by Nightfirecat** [comment]
Re-read my last comment &mdash; try using the email/password combination you would use to log in to www.realmofthemadgod.com directly instead of using the Kongregate credentials method.

**Comment by xAdrenaline** [comment]
Oh okay right now im traveling back to my house from college thanks for your help.  I'll tell you when I try it.

**Comment by xAdrenaline** [comment]
Using the direct email/password combination did work.  Thank you!  In case other people have confusion too, maybe this should be added to the wiki?

**Comment by Nightfirecat** [comment]
From what I remember, I thought it was pretty clear, but I'll revisit them tomorrow and make any necessary edits to make sure that's the case.

**Comment by atomizer** [comment]
Looks like this is resolved.
