### ISSUE TITLE
My accounts don't update

### ISSUE THREAD

**Issue by fejfo** [atomizer/muledump#92]
My account types :
1 steam account
a couple of normal accounts (just created using realmofthemadgod.com)
1 normal account thats actually shows a loading error

What I use :
I use chrome as my browser

What I have tried : 
Using Firefox
reinstalling mule dump
changing the loading site in realmapis
clearing my cookies and such
checked if my steam credentials are correct (using fiddler 2)
check if the password for the 'normal' account that doesn't load is correct

But the interesting part is that I've created a couple of new accounts recently and initially they loaded just fine but they never updated.

**Comment by BlackRayquaza** [comment]
Check the normal accounts using Fiddler

**Comment by fejfo** [comment]
how ? I'm not familiar with the program I just follow the tutorial

**Comment by BlackRayquaza** [comment]
Look for a "realmofthemadgodhrd.appspot.com/char/list" request

**Comment by fejfo** [comment]
I think there ok (I don't know what I exaltly have to look for but the name coralates and cleanPasswordStatus is true( 1 ) I checkt it for a couple account but I don't think there will be a difference between my mules

**Comment by BlackRayquaza** [comment]
Can you check the requests when you load/reload the accounts that dont work? Look for _query.yahooapis.com_

![](http://i.imgur.com/P8FgcQV.png)

![](http://i.imgur.com/n21SVvJ.png)

**Comment by fejfo** [comment]
with some I get the "Error":"Account credentials not valid" but with others I don't and they don't update either an example of the other text :
`1FBC
/**/jQuery21309959507146850228_1454688712187({"query":{"count":1,"created":"2016-02-05T16:09:54Z","lang":"nl-NL","results":{"Chars":{"maxNumChars":"1","nextCharId":"247","Char":{"id":"246","ObjectType":"801","Level":"20","Exp":"888174","CurrentFame":"640","Equipment":"2719,2735,2708,2766,2574,2693,3229,2784,-1,2719,3209,2562,-1,-1,-1,-1,-1,-1,-1","MaxHitPoints":"584","HitPoints":"584","MaxMagicPoints":"310","MagicPoints":"495","Attack":"41","Defense":"0","Speed":"32","Dexterity":"42","HpRegen":"23","MpRegen":"41","PCStats":"AAAClsQBAAJ5JgMAC6IRBAAAAMwGAAAAFwcAAAkUCAAAAE8JAAAZSAwAAAAEEwAAAAgUAAAA9hcAAAAC","HealthStackCount":"0","MagicStackCount":"0","Dead":"False","Pet":{"instanceId":"4","maxAbilityPower":"70","name":"{pets.Pigeon_Skin}","rarity":"2","skin":"32835","type":"32583","Abilities":{"Ability":[{"points":"20847","power":"58","type":"407"},{"points":"7874","power":"46","type":"405"},{"points":"0","power":"1","type":"411"}]}},"casToken":"None","Account":{"Name":"Fejfo"},"XpBoosted":"0","XpTimer":"0","LDTimer":"0","LTTimer":"0","HasBackpack":"0"},"Account":{"Credits":"30","FortuneToken":"0","NextCharSlotPrice":"600","AccountId":"6015534252425216","Vault":{"Chest":"2705,2720,2696,3150,2721,2579,2700,2693"},"Gifts":"3177,3176,3177,3176,3177,3176,3176,3177,3176,3177,3176,3177,3118,3170,8852,3176,3177,3176,3177,3176,3177,3176,3177,3176,3177,3176,3177,3176,3177,3176,3177,3176,3177,3176,3177,3177,3176,3176,3177","Originating":"Steamworks","cleanPasswordStatus":"1","Name":"Fejfo","NameChosen":null,"BeginnerPackageTimeLeft":"0","IsAgeVerified":"1","LastServer":"ec2-54-216-200-98.eu-west-1.compute.amazonaws.com","TeleportWait":"0","PetYardType":"3","ArenaTickets":"0","Stats":{"ClassStats":[{"objectType":"0x300","BestLevel":"20","BestFame":"234"},{"objectType":"0x307","BestLevel":"20","BestFame":"160"},{"objectType":"0x30e","BestLevel":"20","BestFame":"536"},{"objectType":"0x310","BestLevel":"20","BestFame":"401"},{"objectType":"0x31d","BestLevel":"20","BestFame":"240"},{"objectType":"0x31e","BestLevel":"20","BestFame":"386"},{"objectType":"0x31f","BestLevel":"20","BestFame":"488"},{"objectType":"0x320","BestLevel":"20","BestFame":"756"},{"objectType":"0x321","BestLevel":"20","BestFame":"640"},{"objectType":"0x322","BestLevel":"20","BestFame":"486"},{"objectType":"0x323","BestLevel":"20","BestFame":"512"},{"objectType":"0x324","BestLevel":"20","BestFame":"391"},{"objectType":"0x325","BestLevel":"20","BestFame":"622"},{"objectType":"0x326","BestLevel":"20","BestFame":"401"}],"BestCharFame":"756","TotalFame":"13781","Fame":"6551"},"Guild":{"id":"5085307955314688","Name":"Ritrafepobji","Rank":"30"}},"News":{"Item":[{"Icon":"news","Title":"Build 119.3 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/15125","Date":"1321154437"},{"Icon":"news","Title":"Build 119 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/11748","Date":"1318616312"},{"Icon":"news","Title":"Build 118.7 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/9785","Date":"1316811481"},{"Icon":"news","Title":"Build 118.6 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/7001","Date":"1313648853"},{"Icon":"news","Title":"Build 118.3 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/5863","Date":"1312417980"},{"Icon":"news","Title":"Build 117.5 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/4696","Date":"1310452334"},{"Icon":"news","Title":"Build 116.8 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/3692","Date":"1308133063"},{"Icon":"news","Title":"Build 116.5 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/3532","Date":"1307570816"},{"Icon":"news","Title":"Build 116.3 on Testing","TagLine":"click for more info","Link":"http://forums.wildshadow.com/node/3481","Date":"1307402660"}]},"Servers":{"Server":[{"Name":"Testing","DNS":"ec2-54-80-103-75.compute-1.amazonaws.com","Lat":"0.00","Long":"0.00","Usage":"0.00"},{"Name":"Testing2","DNS":"ec2-54-241-233-135.us-west-1.compute.amazonaws.com","Lat":"0.00","Long":"0.00","Usage":"0.00"}]},"Lat":"40.71","Long":"-74.01","KabamPaymentInfo":{"naid":"257515585","signedRequest":"h_EtgIyljVTiGIJ8FS-tJABZS4RPH_CJ9Cd8u1IRMZM.eyJuYWlkIjogIjI1NzUxNTU4NSJ9"},"ClassAvailabilityList":{"ClassAvailability":[{"id":"Rogue","content":"unrestricted"},{"id":"Assassin","content":"unrestricted"},{"id":"Huntress","content":"unrestricted"},{"id":"Mystic","content":"unrestricted"},{"id":"Trickster","content":"unrestricted"},{"id":"Sorcerer","content":"unrestricted"},{"id":"Ninja","content":"unrestricted"},{"id":"Archer","content":"unrestricted"},{"id":"Wizard","content":"unrestricted"},{"id":"Priest","content":"unrestricted"},{"id":"Necromancer","content":"unrestricted"},{"id":"Warrior","content":"unrestricted"},{"id":"Knight","content":"unrestricted"},{"id":"Paladin","content":"unrestricted"}]},"OwnedSkins":"856,902,29800,872","ItemCosts":{"ItemCost":[{"expires":"1","purchasable":"0","type":"900","content":"90000"},{"expires":"1","purchasable":"0","type":"902","content":"90000"},{"expires":"1","purchasable":"0","type":"903","content":"90000"},{"expires":"1","purchasable":"0","type":"904","content":"90000"},{"expires":"1","purchasable":"0","type":"905","content":"90000"},{"expires":"1","purchasable":"0","type":"912","content":"90000"},{"expires":"1","purchasable":"0","type":"913","content":"90000"},{"expires":"1","purchasable":"0","type":"914","content":"90000"},{"expires":"0","purchasable":"1","type":"834","content":"900"},{"expires":"0","purchasable":"1","type":"835","content":"900"},{"expires":"0","purchasable":"1","type":"836","content":"500"},{"expires":"0","purchasable":"1","type":"837","content":"900"},{"expires":"0","purchasable":"1","type":"838","content":"900"},{"expires":"0","purchasable":"1","type":"839","content":"900"},{"expires":"0","purchasable":"1","type":"840","content":"900"},{"expires":"0","purchasable":"1","type":"841","content":"900"},{"expires":"0","purchasable":"1","type":"842","content":"900"},{"expires":"0","purchasable":"1","type":"843","content":"900"},{"expires":"0","purchasable":"1","type":"844","content":"900"},{"expires":"0","purchasable":"1","type":"845","content":"900"},{"expires":"0","purchasable":"1","type":"846","content":"900"},{"expires":"0","purchasable":"1","type":"847","content":"900"},{"expires":"0","purchasable":"1","type":"848","content":"900"},{"expires":"0","purchasable":"0","type":"849","content":"900"},{"expires":"1","purchasable":"0","type":"850","content":"900"},{"expires":"1","purchasable":"0","type":"851","content":"900"},{"expires":"0","purchasable":"1","type":"852","content":"900"},{"expires":"0","purchasable":"1","type":"853","content":"900"},{"expires":"0","purchasable":"1","type":"854","content":"900"},{"expires":"0","purchasable":"1","type":"855","content":"900"},{"expires":"1","purchasable":"0","type":"856","content":"90000"},{"expires":"1","purchasable":"0","type":"883","content":"90000"}]},"SalesForce":"bGlmZXRpbWVfc3BlbmQ9MCZnYW1lX25ldHdvcmtfaWQ9NzY1NjExOTgxMzEyMzI4MzYmbmFpZD0yNTc1MTU1ODUmZ2FtZV9pZD0yNCZwbGF5ZXJfaWQ9JnVzZXJfaWQ9c3RlYW13b3Jrczo3NjU2MTE5ODEzMTIzMjgzNiZkYXRlX2pvaW5lZD0wODI2MjAxNCZwbGF5ZXJfbmFtZT1GZWpmbyZsYW5ndWFnZT1lbiZkZXZpY2VfbW9kZWw9T3RoZXImZ2FtZV9zaG9ydD1ybWcmZ2FtZV9uZXR3b3JrX25hbWU9c3RlYW0mb3Nfc3lzdGVtPU5vdCBBdmFpbGFibGUmcmVsZWFzZT15Y3Rlc3QtMjAxNTEyMDgxMjMwLTVjNDQ5OWIuMzg5MTI2MTk1MDgxOTMzNDAx","MaxClassLevelList":{"MaxClassLevel":[{"classType":"768","maxLevel":"20"},{"classType":"801","maxLevel":"20"},{"classType":"802","maxLevel":"20"},{"classType":"803","maxLevel":"20"},{"classType":"804","maxLevel":"20"},{"classType":"805","maxLevel":"20"},{"classType":"806","maxLevel":"20"},{"classType":"775","maxLevel":"20"},{"classType":"782","maxLevel":"20"},{"classType":"784","maxLevel":"20"},{"classType":"799","maxLevel":"20"},{"classType":"797","maxLevel":"20"},{"classType":"798","maxLevel":"20"},{"classType":"800","maxLevel":"20"}]}}}}}
2
);
0

`

**Comment by BlackRayquaza** [comment]
The error means that the email - password combination is invalid, the long JSON is the data for your characters

**Comment by fejfo** [comment]
so what do I have to do ?

**Comment by atomizer** [comment]
Is this still an issue?

**Comment by fejfo** [comment]
No the new version of mule dumb works  fine with  fire fox. I totally forgot about this thread.
