### ISSUE TITLE
One click login. how do i run mulelogin once?

### ISSUE THREAD

**Issue by ROTMGperson** [atomizer/muledump#93]
it says i have to run mulelogin in lib once. but it is a text doc. what am i missing

**Comment by Nightfirecat** [comment]
By "run `lib/mulelogin.au3` once", it means actually open the file itself with AutoIt. Once you've done that, one-click login will work.

**Comment by ROTMGperson** [comment]
@Nightfirecat Thanks so much.

**Comment by Nightfirecat** [comment]
No problem. I'll edit the wiki page later today to make that more clear.
@atomizer This can be closed.
