### ISSUE TITLE
Mac Computer?-Grey Screen I don't know how to fix.

### ISSUE THREAD

**Issue by Alazerp** [atomizer/muledump#95]

**Comment by Alazerp** [comment]
When I open the muledump I think I have done everything correctly i have tried a few times- there is a grey screen in google chrome

**Comment by Nightfirecat** [comment]
Can you open the developer tools console (<kbd>Cmd</kbd> + <kbd>Opt</kbd> + <kbd>I</kbd>) and switch to the "Console" tab, then refresh the page? This should display any errors that are occurring at startup. Please post those in a reply, and we'll see what we can find out.

**Comment by bearz2** [comment]
Uncaught SyntaxError: Unexpected token ILLEGAL
totals.js:338 Unknown item: 2871 Melon Liqueur
totals.js:338 Unknown item: 3321 Pet Form Stone

**Comment by bearz2** [comment]
Help

**Comment by Nightfirecat** [comment]
There doesn't seem to be any text "ILLEGAL" in Muledump itself. Does the console describe what file this syntax error is being caused by? I would suggest double-checking your `accounts.js` file for any mistypes or errors.

**Comment by Alazerp** [comment]
Should I do the cmd opt I in the grey muledump screen

**Comment by Nightfirecat** [comment]
Yes.

**Comment by Alazerp** [comment]
Uncaught SyntaxError: Unexpected token ILLEGAL
totals.js:338 Unknown item: 2871 Melon Liqueur
totals.js:338 Unknown item: 3321 Pet Form Stone

This is what came up? Help please :100:

**Comment by BlackRayquaza** [comment]
Lovely, errors that tell you nothing useful.

**Comment by Nightfirecat** [comment]
[Give this StackOverflow question a read](http://stackoverflow.com/questions/12719859/no-visible-cause-for-unexpected-token-illegal) and let me know if it helps. Check your file for any invisible characters with your text editor. If need be, re-download the `accounts_sample.js` file from the repo, and modify that.

**Comment by Alazerp** [comment]
I have no idea how to do that

**Comment by Nightfirecat** [comment]
Without seeing your `accounts.js` file, I can only say that the error that's showing up is caused by using improper characters. Whether that's because of strange space characters (zero-width spaces), fancy quotes, or some other type of non-standard character, I can't say.

Again, I recommend re-downloading the `accounts_sample.js` file, renaming it `accounts.js`, and replacing the existing sample accounts with your actual accounts. This is likely to yield a correct configuration.
