### ISSUE TITLE
Grey Screen help please

### ISSUE THREAD

**Issue by bearz2** [atomizer/muledump#96]
Im using chrome and i put muledump onto my browser but only a small square appears instead of what actually is supposed to appear. I have my mule open and i have an error. Grey screen

Please help,
bear

**Comment by bearz2** [comment]
Uncaught SyntaxError: Unexpected token ILLEGAL
totals.js:338 Unknown item: 2871 Melon Liqueur
totals.js:338 Unknown item: 3321 Pet Form Stone

**Comment by Nightfirecat** [comment]
See https://github.com/atomizer/muledump/issues/95#issuecomment-191305826

**Comment by atomizer** [comment]
Looks like you broke syntax in `accounts.js`. Make sure both of the curly braces are there, that every email and password is in quotes, and that there are no missing commas or colons.

**Comment by bearz2** [comment]
there isnt any missing commas or colons

**Comment by bearz2** [comment]
what are curly braces....

**Comment by bearz2** [comment]
here ill show you what ive done

**Comment by bearz2** [comment]
i really dont care if you hack me so

**Comment by bearz2** [comment]
‘nelice@armyspy.com’: ‘password123’,
'email2': 'pass2',

**Comment by bearz2** [comment]
is that right or wrong? @atomizer @Nightfirecat

**Comment by atomizer** [comment]
You have top commas instead of apostrophes around email and password. Use a normal editor (like Notepad++ or Sublime Text) to avoid this kind of "autocorrect".

**Comment by atomizer** [comment]
And curly braces are these: `{}`

**Comment by bearz2** [comment]
Okay so where to put curly

**Comment by bearz2** [comment]
"nelice@armyspy.com": "password123",
"email2": "pass2"

**Comment by atomizer** [comment]
Just replace everything in `accounts.js` with this:
```javascript
accounts = {
"nelice@armyspy.com": "password123"
}
```

**Comment by bearz2** [comment]
sweet thanks and then do same thing with other mules?

**Comment by atomizer** [comment]
Add them below the first one, but before `}`. Don't forget the quotes, colons and commas in between.

**Comment by atomizer** [comment]
I'm having flashbacks of working tech support. *shudders*

**Comment by bearz2** [comment]
{“nelice@armyspy.com": "password123”}
{“email2": "pass2”}

 :) so like this :

**Comment by atomizer** [comment]
No, like this:
```javascript
accounts = {
"nelice@armyspy.com": "password123",
"another@account": "HiMom!",
"whatever@else": "youmighthave",
"feel@free.to": "add as many as you want",
"hopefully@this.is": "cl34r-3N0ugh"
}
```
You can expect me to stop taking you seriously very soon.

**Comment by bearz2** [comment]
lol okay

**Comment by bearz2** [comment]
im bad at this...

**Comment by bearz2** [comment]
i think i get it

**Comment by bearz2** [comment]
{
"nelice@armyspy.com": "password123",
"": "",
"": "",
“”: "",
"": “”
}

**Comment by bearz2** [comment]
Uncaught SyntaxError: Unexpected token { @atomizer im sorry.... i did something wrong...

**Comment by Nightfirecat** [comment]
If your only account is `nelice@armyspy.com`, just use the following:

    accounts = {
    "nelice@armyspy.com": "password123"
    }

If you have more accounts, use this:

    accounts = {
    "nelice@armyspy.com": "password123",
    "account2@kabam.com": "secondpassword!",
    "testaccount@github.com": "testpassword"
    }

**Comment by bearz2** [comment]
thanks so much im such a pain in the butt :)

**Comment by bearz2** [comment]
ill tell you if im doing crap wrong again

**Comment by bearz2** [comment]
Hey @Nightfirecat i still need help. I configured 3 accounts including first one i drag muledump into browser and then it says :Uncaught SyntaxError: Unexpected token {

**Comment by bearz2** [comment]
{
"nelice@armyspy.com": "password123",
“nelice2@armyspy.com”: “password1234”,
“nelice3@armyspy.com”: “password12345”
}
you told me to use this so i am using it

**Comment by Nightfirecat** [comment]
Make sure that **your full `accounts.js` file** looks like this:


```
accounts = {
"nelice@armyspy.com": "password123",
"nelice2@armyspy.com": "password1234",
"nelice3@armyspy.com": "password12345"
}// don't delete this line!

rowlength = 7
testing = 0
prices = 0
mulelogin = 0
nomasonry = 0
```

## Be sure that you are using a normal text editor to save this file!

It seems that you have some 'fancy quotes' which will not work properly.

**Comment by bearz2** [comment]
LOL I AM SORRY

**Comment by bearz2** [comment]
im using text edit on a mac

**Comment by bearz2** [comment]
what do you think i should use?

**Comment by bearz2** [comment]
holdup dont say

**Comment by bearz2** [comment]
sublime text... gotcha

**Comment by bearz2** [comment]
@Nightfirecat okay i have everything ready i fixed the fancy quotations and crap but it still says : Uncaught SyntaxError: Unexpected token {

**Comment by bearz2** [comment]
the unexpected token is the { so im confused

**Comment by bearz2** [comment]
I DID IT!!! OMG YES

**Comment by bearz2** [comment]
THANKS SO MUCH @atomizer and @Nightfirecat  !!!! OMG FNALLY

**Comment by bearz2** [comment]
@atomizer @Nightfirecat now how do you multibox on it or does it just show the stats...

**Comment by atomizer** [comment]
No, you can't multibox with muledump.
