### ISSUE TITLE
Grey Screen Issue Windows 10 OS

### ISSUE THREAD

**Issue by OVBDavid** [atomizer/muledump#99]
Hello any Muledump Moderator/Admin,

I am currently having the issue of getting my Muledump.html file to work properly.

The Setup I have so far includes:
- accoutns_sample.js file changed to accounts. 
- inside that file my information looks as follows:
accounts = {
"*********": "password123",
}

rowlength = 7
testing = 0
prices = 0
mulelogin = 0
nomasonry = 0

- My I have logged out and reloaded my flash projector 100s of times with my account relogging and logging out of my account in-game
- Whenever I try to open the muledump.html file it just opens up to the muledump page that is grey with a little box in the left hand corner with nothing else.

I apologize for this post being so long, but I have scoured multiple forums in hopes of finding an answer somewhere, but I just cannot find anything for the life of me. Is there anyway one of you could help me?

Regards,

OVBDavid

**Comment by Nightfirecat** [comment]
Can you open your browser's console? (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> in most browsers), open the "Console" tab, and refresh the page? There should be an error logged there.

**Comment by OVBDavid** [comment]
Thank you, if it continues to grey screen on chrome should I try another trouble shoot? Thank you for your help already @Nightfirecat ! My laptop is currently being repaired, but when I get it back I will try again!

**Comment by Nightfirecat** [comment]
Just let us know the error message and we can probably deduce from there what the issue is.

**Comment by ShowTek** [comment]
I am having the same problem and this is the error for me : 

GET file:///C:/Users/Jo%C3%A3o/Desktop/atomizer-muledump-ebebfc9/accounts.js net::ERR_FILE_NOT_FOUND
totals.js:338 Unknown item: 2871 Melon Liqueur
totals.js:338 Unknown item: 3321 Pet Form Stone


if u could help that would be nice :)

**Comment by Nightfirecat** [comment]
> GET file:///C:/Users/Jo%C3%A3o/Desktop/atomizer-muledump-ebebfc9/accounts.js

Sounds like your accounts.js file is misplaced or misnamed.

**Comment by ShowTek** [comment]
The file name is like this ( accounts.js )

**Comment by Nightfirecat** [comment]
Yup, looks like [you have your Windows extensions turned off](https://github.com/atomizer/muledump/wiki/Troubleshooting#it-shows-nothing-what-did-i-do-wrong), so renaming the file to `accounts` *really* changed the actual name to `accounts.js` rather than `accounts.js.js`.

**Comment by OVBDavid** [comment]
I'm getting the same error, but my file was already renamed to "accounts" and it still didn't work. Am I supposed to have windows extensions turned on? I followed the link you added into your post and I just don't know what else to do at this point.

**Comment by Nightfirecat** [comment]
Well, that's odd. Glad it all got worked out in the end!

**Comment by TurboJonsson** [comment]
I have this problem, hope someone can help me :)
https://gyazo.com/f3d3a9f855f458bd86b5087cfc42f047

**Comment by Nightfirecat** [comment]
[As you can see, RotMG is down for maintenance.](http://www.realmofthemadgod.com/) You will not be able to get your account data until it is back online.
